on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Grab binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/amd64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]
        exclude:
          - goarch: "386"
            goos: darwin
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Read Go versions
        run: echo "##[set-output name=go_version;]$(cat .github/versions/go)"
        id: go_versions

      - name: Add Go binaries to release
        uses: wangyoucao577/go-release-action@v1.18
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: ${{ steps.go_versions.outputs.go_version }}
          binary_name: "grab"
          sha256sum: true
          md5sum: false
          extra_files: LICENSE README.md
